<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => '100” 4K DB100 TV Black Frame, Back & Glass',
                'quantity' => 1,
                'trade_price' => 32083.10,
                'retail_price' => 54999.60,
                'mpn' => '',
                'sku' => 'DB100BB',
            ],
            [
                'name' => '100” 4K DB100 TV White Frame, Back & Glass',
                'quantity' => 1,
                'trade_price' => 32083.10,
                'retail_price' => 54999.60,
                'mpn' => '',
                'sku' => 'DB100WW',
            ],
            [
                'name' => 'AIM8 TWO Series 2, 8" 2-way, In-Ceiling Speaker',
                'quantity' => 4,
                'trade_price' => 786.68,
                'retail_price' => 2360.00,
                'mpn' => 'AIM282',
                'sku' => '',
            ],
            [
                'name' => 'Cinema 100 CT System (240V)',
                'quantity' => 1,
                'trade_price' => 550.89,
                'retail_price' => 1322.14,
                'mpn' => '1019000001',
                'sku' => '',
            ],
            [
                'name' => 'Control4® EA-5 Entertainment and Automation Controller, V2',
                'quantity' => 1,
                'trade_price' => 1054.95,
                'retail_price' => 1768.96,
                'mpn' => 'C4-EA5-V2',
                'sku' => 'C4-EA5-V2',
            ],
            [
                'name' => 'DIN-2MC2',
                'quantity' => 1,
                'trade_price' => 301.00,
                'retail_price' => 722.40,
                'mpn' => '6501745',
                'sku' => '',
            ],
            [
                'name' => 'Décor-1SC-(90-130in)',
                'quantity' => 1,
                'trade_price' => 1433.24,
                'retail_price' => 3439.77,
                'mpn' => '1210000042',
                'sku' => '',
            ],
            [
                'name' => 'ELA SC 200 ZW',
                'quantity' => 2,
                'trade_price' => 1572.88,
                'retail_price' => 4000.00,
                'mpn' => 'EL-SC-200-ZW',
                'sku' => '',
            ],
            [
                'name' => 'ELA-IP-IDV2-WH',
                'quantity' => 1,
                'trade_price' => 216.27,
                'retail_price' => 415.99,
                'mpn' => 'EL-IP-IDV2-WH',
                'sku' => '',
            ],
            [
                'name' => 'ELA-IP-ODA4-BK',
                'quantity' => 1,
                'trade_price' => 278.07,
                'retail_price' => 533.89,
                'mpn' => 'EL-IP-ODA4-BK',
                'sku' => '',
            ],
            [
                'name' => 'ELA-IP-ODA4-WH',
                'quantity' => 2,
                'trade_price' => 578.40,
                'retail_price' => 1067.98,
                'mpn' => 'EL-IP-ODA4-WH',
                'sku' => '',
            ],
            [
                'name' => 'ELA-NVR-2TB',
                'quantity' => 1,
                'trade_price' => 660.37,
                'retail_price' => 1282.99,
                'mpn' => 'EL-NVR-2TB',
                'sku' => '',
            ],
            [
                'name' => 'Episode Mini AV Receiver | 5.1 Channel',
                'quantity' => 2,
                'trade_price' => 982.50,
                'retail_price' => 1787.88,
                'mpn' => 'EA-MINI-5.1D-200',
                'sku' => 'EA-MINI-5.1D-200',
            ],
            [
                'name' => 'KLI-CS-16-CSM',
                'quantity' => 1,
                'trade_price' => 90.96,
                'retail_price' => 220.50,
                'mpn' => '1064162',
                'sku' => '',
            ],
            [
                'name' => 'KOR-BRAVO-HDMI-1.5',
                'quantity' => 2,
                'trade_price' => 80.04,
                'retail_price' => 115.98,
                'mpn' => 'Bravo-HD0150',
                'sku' => '',
            ],
            [
                'name' => 'MCA 525 v2',
                'quantity' => 2,
                'trade_price' => 4073.70,
                'retail_price' => 8147.40,
                'mpn' => '1412000033',
                'sku' => '',
            ],
            [
                'name' => 'Neeo Remote for Control4 (Black)',
                'quantity' => 2,
                'trade_price' => 705.60,
                'retail_price' => 1175.90,
                'mpn' => 'NE-RMT-BL',
                'sku' => 'NE-RMT-BL',
            ],
            [
                'name' => 'PRO-16RC',
                'quantity' => 5,
                'trade_price' => 808.50,
                'retail_price' => 1942.50,
                'mpn' => '1064446',
                'sku' => '',
            ],
            [
                'name' => 'PRO-180RPC IN-CEILING SPEAKER',
                'quantity' => 10,
                'trade_price' => 2543.40,
                'retail_price' => 6125.00,
                'mpn' => '1063967',
                'sku' => 'KLI-PRO-180RPC',
            ],
            [
                'name' => 'PRO-18RC',
                'quantity' => 3,
                'trade_price' => 565.95,
                'retail_price' => 1365.00,
                'mpn' => '1064447',
                'sku' => '',
            ],
            [
                'name' => 'Pakedge 24 Port Managed Switch with 24 PoE or 12 PoE+ Ports EOS',
                'quantity' => 1,
                'trade_price' => 761.45,
                'retail_price' => 1272.95,
                'mpn' => 'SX-24P',
                'sku' => 'SX-24P',
            ],
            [
                'name' => 'RAK-RAK-LINK',
                'quantity' => 1,
                'trade_price' => 275.10,
                'retail_price' => 393.00,
                'mpn' => 'RAK-LINK',
                'sku' => '',
            ],
            [
                'name' => 'RAK-RAK8-MB',
                'quantity' => 1,
                'trade_price' => 295.40,
                'retail_price' => 422.00,
                'mpn' => 'RAK8-MB',
                'sku' => '',
            ],
            [
                'name' => 'RAK-RCM-070 (Black Nickel)',
                'quantity' => 5,
                'trade_price' => 637.00,
                'retail_price' => 1092.00,
                'mpn' => '',
                'sku' => '',
            ],
            [
                'name' => 'RAK-WCM-070 (Black Nickel)',
                'quantity' => 1,
                'trade_price' => 166.60,
                'retail_price' => 285.60,
                'mpn' => '',
                'sku' => '',
            ],
            [
                'name' => 'RAK-WDA-600',
                'quantity' => 1,
                'trade_price' => 74.20,
                'retail_price' => 127.20,
                'mpn' => 'WDA-600',
                'sku' => '',
            ],
            [
                'name' => 'RAK-WML-300',
                'quantity' => 3,
                'trade_price' => 222.60,
                'retail_price' => 381.60,
                'mpn' => 'WML-300',
                'sku' => '',
            ],
            [
                'name' => 'RAK-WMT-400',
                'quantity' => 2,
                'trade_price' => 148.40,
                'retail_price' => 254.40,
                'mpn' => 'WMT-400',
                'sku' => '',
            ],
            [
                'name' => 'SLM-3400-C',
                'quantity' => 1,
                'trade_price' => 188.65,
                'retail_price' => 455.00,
                'mpn' => '1063200',
                'sku' => '',
            ],
            [
                'name' => 'Strong Carbon Series H-Bracket Adapter for Articulating Mounts',
                'quantity' => 1,
                'trade_price' => 23.65,
                'retail_price' => 74.95,
                'mpn' => 'SM-CB-H-BKT',
                'sku' => 'SM-CB-H-BKT',
            ],
            [
                'name' => 'Strong Custom Series Floor Standing Rack - 20" Depth | 42U',
                'quantity' => 1,
                'trade_price' => 258.75,
                'retail_price' => 758.95,
                'mpn' => 'SR-CUSTOM-42U-20IN',
                'sku' => 'SR-CUSTOM-42U-20IN',
            ],
            [
                'name' => 'UBI-UAP-AC-HD',
                'quantity' => 3,
                'trade_price' => 695.13,
                'retail_price' => 981.36,
                'mpn' => 'UAP-AC-HD',
                'sku' => '',
            ],
            [
                'name' => 'UBI-UAP-AC-NANOHD',
                'quantity' => 1,
                'trade_price' => 121.94,
                'retail_price' => 172.15,
                'mpn' => 'UAP-nanoHD',
                'sku' => '',
            ],
            [
                'name' => 'WK-HUB',
                'quantity' => 1,
                'trade_price' => 263.90,
                'retail_price' => 377.00,
                'mpn' => 'WK-HUB',
                'sku' => '',
            ],
            [
                'name' => 'neo:Lite 70m Extender Set',
                'quantity' => 1,
                'trade_price' => 140.00,
                'retail_price' => 282.00,
                'mpn' => 'P8-HDBT-L-EXSET',
                'sku' => '',
            ],
            [
                'name' => 'neo:Lite HDMI Extender Set',
                'quantity' => 1,
                'trade_price' => 140.00,
                'retail_price' => 282.00,
                'mpn' => 'P8-HDBT-L-EXSET',
                'sku' => '',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
