<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => '100” 4K DB100 TV Black Frame, Back & Glass',
                'quantity' => 1,
                'trade_price' => 32083.1,
                'retail_price' => 54999.6,
                'mpn' => '',
                'sku' => 'DB100BB',
                'category' => 'Displays & TVs',
            ],
            [
                'name' => '100” 4K DB100 TV White Frame, Back & Glass',
                'quantity' => 1,
                'trade_price' => 32083.1,
                'retail_price' => 54999.6,
                'mpn' => '',
                'sku' => 'DB100WW',
                'category' => 'Displays & TVs',
            ],
            [
                'name' => 'AIM8 TWO Series 2, 8" 2-way, In-Ceiling Speaker',
                'quantity' => 4,
                'trade_price' => 786.68,
                'retail_price' => 2360.0,
                'mpn' => 'AIM282',
                'sku' => '',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'Cinema 100 CT System (240V)',
                'quantity' => 1,
                'trade_price' => 550.89,
                'retail_price' => 1322.14,
                'mpn' => '1019000001',
                'sku' => '',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'Control4® EA-5 Entertainment and Automation Controller, V2',
                'quantity' => 1,
                'trade_price' => 1054.95,
                'retail_price' => 1768.96,
                'mpn' => 'C4-EA5-V2',
                'sku' => 'C4-EA5-V2',
                'category' => 'Control & Automation',
            ],
            [
                'name' => 'DIN-2MC2',
                'quantity' => 1,
                'trade_price' => 301.0,
                'retail_price' => 722.4,
                'mpn' => '6501745',
                'sku' => '',
                'category' => 'Control & Automation',
            ],
            [
                'name' => 'Décor-1SC-(90-130in)',
                'quantity' => 1,
                'trade_price' => 1433.24,
                'retail_price' => 3439.77,
                'mpn' => '1210000042',
                'sku' => '',
                'category' => 'Mounts & Racks',
            ],
            [
                'name' => 'ELA SC 200 ZW',
                'quantity' => 2,
                'trade_price' => 1572.88,
                'retail_price' => 4000.0,
                'mpn' => 'EL-SC-200-ZW',
                'sku' => '',
                'category' => 'Control & Automation',
            ],
            [
                'name' => 'ELA-IP-IDV2-WH',
                'quantity' => 1,
                'trade_price' => 216.27,
                'retail_price' => 415.99,
                'mpn' => 'EL-IP-IDV2-WH',
                'sku' => '',
                'category' => 'Security & Surveillance',
            ],
            [
                'name' => 'ELA-IP-ODA4-BK',
                'quantity' => 1,
                'trade_price' => 278.07,
                'retail_price' => 533.89,
                'mpn' => 'EL-IP-ODA4-BK',
                'sku' => '',
                'category' => 'Security & Surveillance',
            ],
            [
                'name' => 'ELA-IP-ODA4-WH',
                'quantity' => 2,
                'trade_price' => 578.4,
                'retail_price' => 1067.98,
                'mpn' => 'EL-IP-ODA4-WH',
                'sku' => '',
                'category' => 'Security & Surveillance',
            ],
            [
                'name' => 'ELA-NVR-2TB',
                'quantity' => 1,
                'trade_price' => 660.37,
                'retail_price' => 1282.99,
                'mpn' => 'EL-NVR-2TB',
                'sku' => '',
                'category' => 'Security & Surveillance',
            ],
            [
                'name' => 'Episode Mini AV Receiver | 5.1 Channel',
                'quantity' => 2,
                'trade_price' => 982.5,
                'retail_price' => 1787.88,
                'mpn' => 'EA-MINI-5.1D-200',
                'sku' => 'EA-MINI-5.1D-200',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'KLI-CS-16-CSM',
                'quantity' => 1,
                'trade_price' => 90.96,
                'retail_price' => 220.5,
                'mpn' => '1064162',
                'sku' => '',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'KOR-BRAVO-HDMI-1.5',
                'quantity' => 2,
                'trade_price' => 80.04,
                'retail_price' => 115.98,
                'mpn' => 'Bravo-HD0150',
                'sku' => '',
                'category' => 'Cables & Interconnects',
            ],
            [
                'name' => 'MCA 525 v2',
                'quantity' => 2,
                'trade_price' => 4073.7,
                'retail_price' => 8147.4,
                'mpn' => '1412000033',
                'sku' => '',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'Neeo Remote for Control4 (Black)',
                'quantity' => 2,
                'trade_price' => 705.6,
                'retail_price' => 1175.9,
                'mpn' => 'NE-RMT-BL',
                'sku' => 'NE-RMT-BL',
                'category' => 'Control & Automation',
            ],
            [
                'name' => 'PRO-16RC',
                'quantity' => 5,
                'trade_price' => 808.5,
                'retail_price' => 1942.5,
                'mpn' => '1064446',
                'sku' => '',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'PRO-180RPC IN-CEILING SPEAKER',
                'quantity' => 10,
                'trade_price' => 2543.4,
                'retail_price' => 6125.0,
                'mpn' => '1063967',
                'sku' => 'KLI-PRO-180RPC',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'PRO-18RC',
                'quantity' => 3,
                'trade_price' => 565.95,
                'retail_price' => 1365.0,
                'mpn' => '1064447',
                'sku' => '',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'Pakedge 24 Port Managed Switch with 24 PoE or 12 PoE+ Ports EOS',
                'quantity' => 1,
                'trade_price' => 761.45,
                'retail_price' => 1272.95,
                'mpn' => 'SX-24P',
                'sku' => 'SX-24P',
                'category' => 'Networking',
            ],
            [
                'name' => 'RAK-RAK-LINK',
                'quantity' => 1,
                'trade_price' => 275.1,
                'retail_price' => 393.0,
                'mpn' => 'RAK-LINK',
                'sku' => '',
                'category' => 'Lighting Control',
            ],
            [
                'name' => 'RAK-RAK8-MB',
                'quantity' => 1,
                'trade_price' => 295.4,
                'retail_price' => 422.0,
                'mpn' => 'RAK8-MB',
                'sku' => '',
                'category' => 'Lighting Control',
            ],
            [
                'name' => 'RAK-RCM-070 (Black Nickel)',
                'quantity' => 5,
                'trade_price' => 637.0,
                'retail_price' => 1092.0,
                'mpn' => '',
                'sku' => '',
                'category' => 'Lighting Control',
            ],
            [
                'name' => 'RAK-WCM-070 (Black Nickel)',
                'quantity' => 1,
                'trade_price' => 166.6,
                'retail_price' => 285.6,
                'mpn' => '',
                'sku' => '',
                'category' => 'Lighting Control',
            ],
            [
                'name' => 'RAK-WDA-600',
                'quantity' => 1,
                'trade_price' => 74.2,
                'retail_price' => 127.2,
                'mpn' => 'WDA-600',
                'sku' => '',
                'category' => 'Lighting Control',
            ],
            [
                'name' => 'RAK-WML-300',
                'quantity' => 3,
                'trade_price' => 222.6,
                'retail_price' => 381.6,
                'mpn' => 'WML-300',
                'sku' => '',
                'category' => 'Lighting Control',
            ],
            [
                'name' => 'RAK-WMT-400',
                'quantity' => 2,
                'trade_price' => 148.4,
                'retail_price' => 254.4,
                'mpn' => 'WMT-400',
                'sku' => '',
                'category' => 'Lighting Control',
            ],
            [
                'name' => 'SLM-3400-C',
                'quantity' => 1,
                'trade_price' => 188.65,
                'retail_price' => 455.0,
                'mpn' => '1063200',
                'sku' => '',
                'category' => 'Speakers & Audio',
            ],
            [
                'name' => 'Strong Carbon Series H-Bracket Adapter for Articulating Mounts',
                'quantity' => 1,
                'trade_price' => 23.65,
                'retail_price' => 74.95,
                'mpn' => 'SM-CB-H-BKT',
                'sku' => 'SM-CB-H-BKT',
                'category' => 'Mounts & Racks',
            ],
            [
                'name' => 'Strong Custom Series Floor Standing Rack - 20" Depth | 42U',
                'quantity' => 1,
                'trade_price' => 258.75,
                'retail_price' => 758.95,
                'mpn' => 'SR-CUSTOM-42U-20IN',
                'sku' => 'SR-CUSTOM-42U-20IN',
                'category' => 'Mounts & Racks',
            ],
            [
                'name' => 'UBI-UAP-AC-HD',
                'quantity' => 3,
                'trade_price' => 695.13,
                'retail_price' => 981.36,
                'mpn' => 'UAP-AC-HD',
                'sku' => '',
                'category' => 'Networking',
            ],
            [
                'name' => 'UBI-UAP-AC-NANOHD',
                'quantity' => 1,
                'trade_price' => 121.94,
                'retail_price' => 172.15,
                'mpn' => 'UAP-nanoHD',
                'sku' => '',
                'category' => 'Networking',
            ],
            [
                'name' => 'WK-HUB',
                'quantity' => 1,
                'trade_price' => 263.9,
                'retail_price' => 377.0,
                'mpn' => 'WK-HUB',
                'sku' => '',
                'category' => 'Control & Automation',
            ],
            [
                'name' => 'neo:Lite 70m Extender Set',
                'quantity' => 1,
                'trade_price' => 140.0,
                'retail_price' => 282.0,
                'mpn' => 'P8-HDBT-L-EXSET',
                'sku' => '',
                'category' => 'Video Distribution',
            ],
            [
                'name' => 'neo:Lite HDMI Extender Set',
                'quantity' => 1,
                'trade_price' => 140.00,
                'retail_price' => 282.00,
                'mpn' => 'P8-HDBT-L-EXSET',
                'sku' => '',
                'category' => 'Video Distribution',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
